class Tree{
public static void main(String[] args){
	    String str="hello word";
		System.out.println(str);
		String test="Now is the time for all good ";
		System.out.println(test);
		String ball="men to come to the aid of their country";
		System.out.println(ball);
		String doll="Time heals ";
		System.out.println(doll);
		String brush="Love conquers.";
		System.out.println(brush);
		String jug="Dream big.";
		System.out.println(jug);
		String laptop="Stay strong.";
		System.out.println(laptop);
		String bag="Be kind.";
		System.out.println(bag);
		String dog="Chase joy";
		System.out.println(dog);
		String pen="Learn daily";
		System.out.println(pen);
		String mobile="Forgive often.";
		System.out.println(mobile);
		String sky="Believe in yourself.";
		System.out.println(sky);
		String kite="Find your passion.";
		System.out.println(kite);	
		String blue="Seek adventure.";
		System.out.println(blue);
		String girl="Trust your journey.";
		System.out.println(girl);
		String boy="Create happiness.";
		System.out.println(boy);
		String bottle="Listen more.";
		System.out.println(bottle);
		String pant="Speak kindly.";
		System.out.println(pant);
		String clip="Celebrate life.";
		System.out.println(clip);
		String teddy="Enjoy the moment.";
		System.out.println(teddy);
		String top="Keep moving forward.";
		System.out.println(top);
		String mirror="Never give up.";
		System.out.println(mirror);
		String animal="Breathe deeply.";
		System.out.println(animal);
		String towel="Live authentically.";
		System.out.println(towel);
		String handel="Be courageous.";
		System.out.println(handel);
		String box="Grow through challenges.";
		System.out.println(box);
		String chain="Be the light.";
		System.out.println(chain);
		String wire="Stay humble.";
		System.out.println(wire);
		String krutha="Follow your heart.";
		System.out.println(krutha);
		String tv="Dance in the rain.";
		System.out.println(tv);
		String ac="Find beauty everywhere.";
		System.out.println(ac);
		String earphone="Radiate positivity.";
		System.out.println(earphone);
		String window="Spread kindness.";
		System.out.println(window);
		String bulb="Value relationships.";
		System.out.println(bulb);	
		String watch="Be present.";
		System.out.println(watch);
		String band="Laugh often.";
		System.out.println(band);
		String finger="Stay curious.";
		System.out.println(finger);
		String hair="Savor simplicity.";
		System.out.println(hair);
		String bed="Practice gratitude.";
		System.out.println(bed);
		String plate="Discover inner peace.";
		System.out.println(plate);
		String city="Inspire others.";
		System.out.println(city);		
		String ring="Count your blessings.";
		System.out.println(ring);
		String soap="Choose happiness.";
		System.out.println(soap);	
		String comb="Stay focused.";
		System.out.println(comb);
		String greating="goodmorning.";
		System.out.println(greating);	
		String clg="angadi institute of technology and management";
		System.out.println(clg);
		String usn="2ag20cs020";
		System.out.println(usn);
		String stream="cse";
		System.out.println(stream);
		String degree="be";
		System.out.println(degree);
		String glass="drinking water";
		System.out.println(glass);
		String area="rajaji nagar";
		System.out.println(area);
		String address="gokak";
		System.out.println(address);
		String pincode="591307";
		System.out.println(pincode);
		String cuntury="india";
		System.out.println(cuntury);
		String cunturycode="91";
		System.out.println(cunturycode);
		String bangle="green colour  ka bangle";
		System.out.println(bangle);
		String fruits="mango bannana apple";
		System.out.println(fruits);
		String vegetables="potato ladiesfinger chilly";
		System.out.println(vegetables);
		String materials="bed chair etc";
		System.out.println(materials);
		String earth="The Earth orbits the Sun at an average distance of about 93 million miles.";
		System.out.println(earth );
		String freezes="Water freezes at 0 degrees Celsius and boils at 100 degrees Celsius.";
		System.out.println(freezes);
		String mountEverest= "Mount Everest is the highest mountain in the world, standing at 8,848 meters.";
		System.out.println(mountEverest);
		String humanBrain="The human brain consists of approximately 86 billion neurons.";
		System.out.println(humanBrain);
		String typesOfBloodGroups="A B AB";
		System.out.println(typesOfBloodGroups);
		String  wall ="The Great Wall of China is over 13,000 miles long.";
		System.out.println(wall);
		String smallestBones="ear bone";
		System.out.println(smallestBones);
		String seeds="fennel sunflower";
		System.out.println(seeds);
		String wifi="many people can access";
		System.out.println(wifi);
		String bucket="for Bath";
		System.out.println(bucket);
		String sweet="for eating";
		System.out.println(sweet);
		String shampo="for hair used";
		System.out.println(shampo);
		String lipstick="for lips";
		System.out.println(lipstick);
		String wine="for chill";
		System.out.println(wine);
		String butterfly="beautiful";
		System.out.println(butterfly);
		String sheva=" masala tasty";
		System.out.println(sheva);
		String shoes="for running";
		System.out.println(shoes);
		String world="for travelling";
		System.out.println(world);
		String pillow="sleeping purpose";
		System.out.println(pillow);
		String eyeshadow="used for eye makeup";
		System.out.println(eyeshadow);
		String bangles="hand look gorgeous";
		System.out.println(bangles);
		String curtain="window closing";
		System.out.println(curtain);
		String fan="for air";
		System.out.println(fan);
		String cream="very tasty";
		System.out.println(cream);
		String eartops="for ear we can use";
		System.out.println(eartops);
		String blanket="to keep sleeping person warm";
		System.out.println(blanket);
		String cold="winter season";
		System.out.println(cold);
		String summer="sun is hot";
		System.out.println(summer);
		String water="for health good";
		System.out.println(water);
		String black="fav colour";
		System.out.println(black);
		String bike="riding";
		System.out.println(bike);
		String tab="for working";
		System.out.println(tab);
		String whatsapp="chatting";
		System.out.println( whatsapp);
		String insta="scrolling";
		System.out.println(insta);
		String tiger="cruel";
		System.out.println(tiger);
		String cow=" god";
		System.out.println(cow);
		String jamoon="very tasty";
		System.out.println(jamoon);
}
}